[[main]]
name = "Features"
identifier = "features"
url = "/features/"
weight = 10

[[main]]
name = "Pricing"
identifier = "pricing"
url = "/pricing/"
weight = 20

[[main]]
name = "About"
identifier = "about"
url = "/about/"
weight = 30

[[main]]
name = "Contact"
identifier = "contact"
url = "/contact/"
weight = 40
